name: Mine4ever
author: Jerry Liang
#baseurl: ""
description: Jerry小站
github: https://github.com/Mine4ever
twitter: http://www.twitter.com/
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
email: Mine4ever97[at]foxmail.com

##Make sure to edit the above fields, especially for disqus.


highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

comment:
  disqus: mine4ever

featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# Baidu 统计 （自己百度搜索百度统计获得自己的追踪代码）
ba_track_id: 8d9720b5c989c12b0a9429dc93086e46

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
