name: Mine4ever
author: Jerry Liang
baseurl: ""
description: Jerry小站
github: https://github.com/Mine4ever
twitter: http://www.twitter.com/
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
email: Mine4ever97[at]foxmail.com

##Make sure to edit the above fields, especially for disqus.


highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Comment
comment:
    disqus: mine4ever
# friends: [
#     {
#         title: "flyzy小站",
#         href: "https://www.flyzy2005.cn"
#     },{
#         title: "Louis的iOS开发小站",
#         href: "http://louisly.com"
#     }
# ]
